export const cities = [
  { city: "Auckland" },
  { city: "Bordeaux" },
  { city: "Brussels" },
  { city: "Burgas" },
  { city: "Cali" },
  { city: "Cartagena" },
  { city: "Dublin" },
  { city: "Edinburgh" },
  { city: "Hangzhou" },
  { city: "Hildesheim" },
  { city: "Hong Kong" },
  { city: "Hurghada" },
  { city: "Iquique" },
  { city: "Jaipur" },
  { city: "Kobe" },
  { city: "Koh Samet" },
  { city: "Kyoto" },
  { city: "Las Vegas (NV)" },
  { city: "Leon" },
  { city: "Lima" },
  { city: "London" },
  { city: "Macau" },
  { city: "Madrid" },
  { city: "Malaga" },
  { city: "Medellin" },
  { city: "Mombasa" },
  { city: "Munakata" },
  { city: "Nara" },
  { city: "New Delhi and NCR" },
  { city: "Nice" },
  { city: "Pittsburgh (PA)" },
  { city: "Rome" },
  { city: "Round Rock (TX)" },
  { city: "Sanremo" },
  { city: "Santa Margherita Ligure" },
  { city: "Seinajoki" },
  { city: "Shanghai" },
  { city: "So Burlington (VT)" },
  { city: "St. Julian's" },
  { city: "Taipei" },
  { city: "Taxco" },
  { city: "Tokyo" },
  { city: "Torremolinos" },
  { city: "Visakhapatnam" },
];
